title: Seogyeong Jeong
url: "https://seogyeongjeong.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://seogyeongjeong.github.io/"
footer_text: "SEOGYEONGJEONG"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/SeogyeongJeong/"
 - name: "CV"
   link: "CV_Seogyeong_Jeong.pdf"
 - name: "Contact"
   link: "contact"
