title: Seogyeong Jeong
description: NLP researcher
site_title: '@site - Seogyeong Jeong'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: seogyeongjeong
# blog_url: https://www.nagekar.com
email: clarajeong@kaist.ac.kr
# keybase_username: abhn
twitter_username: evelynjeong888
reddit_username: evelynjeong8

# absolute or relative
profile_picture: profile_seogyeong.jpg

# Google Analytics ID
google_analytics: 